#include "TestClass.h"
#include "DeriveTest.h"

REFLECT_START(IImp)
REFLECT_END

REFLECT_START_SUPER(DeriveTest)
REFLECT_END

REFLECT_START_SUPER(Derive2Test)
REFLECT_END

REFLECT_START_SUPER(DTest)
REFLECT_END

REFLECT_START_SUPER_MULTI(TTest, TypeResolver<IImp>::get())
REFLECT_END


REFLECT_START_SUPER(GCObject)
REFLECT_END

REFLECT_START_SUPER(GCObjectable)
REFLECT_PROPERTY(buddy)
REFLECT_PROPERTY(buddy2)
REFLECT_PROPERTY(dude)
REFLECT_END

REFLECT_START(poss)
REFLECT_METHOD(overrid)
REFLECT_FUNCTION(New)
REFLECT_PROPERTY(truea)
REFLECT_END


REFLECT_START_SUPER(OK)
REFLECT_END

REFLECT_START_SUPER(OKDobule)
REFLECT_METHOD(zep)
REFLECT_END

void DeriveTest::overrid(int a)
{
	std::cout << "fool " << a << '\n';
}

void Derive2Test::overrid(int a) {

	std::cout << "idiot " << a << '\n';
}